// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcnxxexwodpnndgbizuz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjbnh4ZXh3b2Rwbm5kZ2JpenV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2ODE4NjcsImV4cCI6MjA2NDI1Nzg2N30.4OI3WzPSe4EMmA-FdLQuKSjS_oe-gtiDAnosb92FLRY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);